#! /bin/sh

# This is the main LaTeXMake script. It calls gnu make
# with the makefile containing the LaTeX dependency rules.
# Mike Buksas and Brendt Wohlberg
# Most recent modification: 21 June 2006

SILENTMODE=0
while [ $# -gt 0 ]
do
    case "$1" in
	-s | --silent) SILENTMODE=1;;
	-h | --help | -*)
            echo >&2 "LaTeXMake 0.14"
	    echo >&2 "usage: $0 [-h|--help] [-s|--silent] [all|ps|pdf|clean}"
            exit 1;;
	*) break;;
    esac
    shift
done
export SILENTMODE
prefix=./
datadir=${prefix}/share
latexmkdir=${datadir}/latexmake
TEXINPUTS=${TEXINPUTS}:${latexmkdir}:.//
export TEXINPUTS
TEXPSHEADERS=${TEXPSHEADERS}:.//
export TEXPSHEADERS
BSTINPUTS=${BSTINPUTS}:.//
export BSTINPUTS
gmake -f ${latexmkdir}/Makefile.latexmk $@
