#! /usr/bin/env bash
################################################################################
# Copyright (c) 2012 Los Alamos National Security, LLC
# All rights reserved.
################################################################################

rm -rf aclocal.m4
rm -rf autom4te.cache
rm -rf configure
rm -rf configure.ac
rm -rf config/config.guess
rm -rf config/config.sub
rm -rf config/depcomp
rm -rf config/install-sh
rm -rf config/ltmain.sh
rm -rf config/missing
rm -rf lib/Makefile.am
rm -rf test/Makefile.am
rm -rf `find . -type f -name "Makefile.in" | grep -v ".git"`
rm -rf `find . -type f -name "Makefile" | grep -v ".git"`
rm -rf `find test -type f -name "testsuite.at" | grep -v ".git"`
rm -rf `find test -type f -name "atlocal.in" | grep -v ".git"`
rm -rf `find test -type f -name "Makefile" | grep -v ".git"`
rm -rf `find test -type f -name "Makefile.in" | grep -v ".git"`
rm -rf src/include
