#!/bin/sh
#
# Written by:
#   Kevin J. Bowers, Ph.D.
#   Plasma Physics Group (X-1)
#   Applied Physics Division
#   Los Alamos National Lab
# March/April 2004 - Original version

rm Makefile
imake -DMACHINE=machine/$1
gmake clean
gmake -j2 all
# make clean
# make all
