#!/bin/sh
#
# Written by:
#   Kevin J. Bowers, Ph.D.
#   Plasma Physics Group (X-1)
#   Applied Physics Division
#   Los Alamos National Lab
# March/April 2004 - Original version

autoconf=`head -n 1 machine/$1 | grep autoconf | sed 's,#,,g'`

if [ -n "$autoconf" ] ; then
	./configure --with-machine=$1
	make clean
	make
	cp lib/.libs/*.a .
else
	rm Makefile
	imake -DMACHINE=machine/$1
	gmake clean
	gmake -j2 all
	# make clean
	# make all
fi
