#! /usr/bin/env bash
#
# Create build system using GNU autotools
#

# create include dir with links
#(cd src ; rm -rf include ; mkdir include ; cd include; \
#	for file in `cat ../../config/spe_header_list` ; do \
#		link=`echo $file`
#		ln -s $link .
#	done
#)

echo "calling libtoolize..."
libtoolize -f --automake
echo "calling aclocal -I $1/m4"
aclocal -I $1/m4 > /dev/null 2>&1
echo "automake -af --foreign"
automake -af --foreign
echo "autoconf"
autoconf
