#! /usr/bin/env bash
#
# Create build system using GNU autotools
#

echo "generating Makefile.am for PPU VPIC library"
[ ! -d lib ] && mkdir lib
config/create_lib_am > lib/Makefile.am

echo "calling libtoolize..."
glibtoolize --version &> /dev/null && LIBTOOLIZE=glibtoolize || LIBTOOLIZE=libtoolize

# older versions of libtoolize use configure.in
$LIBTOOLIZE -c -n -f --automake &> /dev/null || ln -s configure.ac configure.in

# actually call libtoolize
$LIBTOOLIZE -c -f --automake

echo "calling aclocal -I $1/m4"
aclocal -I $1/m4 > /dev/null 2>&1

echo "automake -af --foreign"
automake -af --foreign

echo "autoconf"
autoconf
