#!/bin/sh

PPU_CC=/opt/cell/bin/ppu-gcc
PPU_CXX=/opt/cell/bin/ppu-g++
PPU_LD=/opt/cell/bin/ppu-g++
#PPU_CC=/opt/ibmcmp/xlc/8.2/bin/ppugxlc
#PPU_CXX=/opt/ibmcmp/xlc/8.2/bin/ppugxlc++
#PPU_LD=/opt/ibmcmp/xlc/8.2/bin/ppugxlc++
PPU_CFLAGS="-Werror -Wall -pedantic -std=c99 -D_XOPEN_SOURCE=600 -g -O2 -fno-strict-aliasing -ffast-math -fno-unsafe-math-optimizations -DUSE_CELL_SPUS"
PPU_CXXFLAGS="-Werror -Wall -pedantic -std=c++98 -D_XOPEN_SOURCE=600 -g -O2 -fno-strict-aliasing -ffast-math -fno-unsafe-math-optimizations -DUSE_CELL_SPUS"
PPU_LDFLAGS="-Werror -Wall -pedantic -std=c99 -D_XOPEN_SOURCE=600 -g -O2 -fno-strict-aliasing -ffast-math -fno-unsafe-math-optimizations -DUSE_CELL_SPUS"

SPU_CC=/opt/cell/bin/spu-gcc
SPU_CXX=/opt/cell/bin/spu-g++
SPU_LD=/opt/cell/bin/spu-gcc
#SPU_CC=/opt/ibmcmp/xlc/8.2/bin/spugxlc
#SPU_CXX=/opt/ibmcmp/xlc/8.2/bin/spugxlc++
#SPU_LD=/opt/ibmcmp/xlc/8.2/bin/spugxlc++
SPU_EM=/opt/cell/bin/ppu-embedspu
SPU_CFLAGS="-Werror -Wall -pedantic -std=c99 -D_XOPEN_SOURCE=600 -g -O2 -fno-strict-aliasing -ffast-math -fno-unsafe-math-optimizations -DUSE_CELL_SPUS"
SPU_CXXFLAGS="-Werror -Wall -pedantic -std=c++98 -Wno-long-long -Wstrict-aliasing=2 -D_XOPEN_SOURCE=600 -O2 -fno-strict-aliasing -ffast-math -fno-unsafe-math-optimizations -fno-exceptions -DUSE_CELL_SPUS -DUSE_V4_SPU"
SPU_LDFLAGS="-Werror -Wall -pedantic -std=c99 -D_XOPEN_SOURCE=600 -g -O2 -fno-strict-aliasing -ffast-math -fno-unsafe-math-optimizations -DUSE_CELL_SPUS"

VPIC=$HOME/src/vpic/src
INCLUDE="-I$VPIC -I$VPIC/util -I$VPIC/util/mtrand -I$VPIC/util/mp -I$VPIC/util/mp/dmp -I$VPIC/util/pipelines -I$VPIC/util/v4 -I$VPIC/grid -I$VPIC/material -I$VPIC/field -I$VPIC/particle -I$VPIC/species -I$VPIC/emitter -I$VPIC/boundary -I$VPIC/vpic -I/opt/ibm/cell-sdk/prototype/sysroot/usr/spu/include"

set -x

rm -f *.o *.spu_obj *.spu_exe *.spu_asm test_v4 *~

$SPU_CXX $SPU_CXXFLAGS $INCLUDE -c $VPIC/util/v4/test_v4.cxx  -o test_v4.spu_obj
$SPU_CXX $SPU_CXXFLAGS $INCLUDE -S -fverbose-asm $VPIC/util/v4/test_v4.cxx -o test_v4.spu_asm
$SPU_LD $SPU_LDFLAGS test_v4.spu_obj -o test_v4.spu_exe
$SPU_EM test_v4 test_v4.spu_exe test_v4_exe.o

$PPU_CC $PPU_CFLAGS $INCLUDE -c test_v4.c         -o test_v4.o
$PPU_LD $PPU_LDFLAGS *.o -o test_v4 -lspe2

