#! /usr/bin/env bash

#------------------------------------------------------------------------------#
# Usage: bootstrap [devel]
#------------------------------------------------------------------------------#

#------------------------------------------------------------------------------#
# Generate configure.ac file
#------------------------------------------------------------------------------#
echo "Generating configure.ac"
config/create_configure_ac $1 > configure.ac

#------------------------------------------------------------------------------#
# Generate Makefile.am in lib directory
#------------------------------------------------------------------------------#
echo "Generating lib/Makefile.am"
[ ! -d lib ] && mkdir lib
config/create_lib_am > lib/Makefile.am

#------------------------------------------------------------------------------#
# Call libtoolize
#------------------------------------------------------------------------------#
echo "Calling libtoolize..."
# check for glibtoolize
glibtoolize --version &> /dev/null && LIBTOOLIZE=glibtoolize || LIBTOOLIZE=libtoolize

# older versions of libtoolize use configure.in
$LIBTOOLIZE -c -n -f --automake &> /dev/null || ln -s configure.ac configure.in

# actually call libtoolize
$LIBTOOLIZE -c -f --automake

#------------------------------------------------------------------------------#
# Call aclocal to generate m4 file
#------------------------------------------------------------------------------#
echo "Calling aclocal -I m4"
aclocal -I m4 > /dev/null 2>&1

#------------------------------------------------------------------------------#
# Call testsuite generation
#------------------------------------------------------------------------------#
echo "Calling testboot"
config/testboot

#------------------------------------------------------------------------------#
# Call autoheader
#------------------------------------------------------------------------------#
#echo "Calling autoheader"
#autoheader

#------------------------------------------------------------------------------#
# Call automake
#------------------------------------------------------------------------------#
echo "Calling automake -af --foreign"
automake -af --foreign -c

#------------------------------------------------------------------------------#
# Call autoconf
#------------------------------------------------------------------------------#
echo "Calling autoconf"
autoconf
