#! /usr/bin/env bash
#
# Create build system using GNU autotools
#

#------------------------------------------------------------------------------#
# generate configure.av file
#------------------------------------------------------------------------------#
echo "generating configure.ac"
config/create_configure_ac $1 > configure.ac

cwd=`pwd`

# create include dir with links
(cd src ; rm -rf include ; mkdir include ; cd include; \
	for file in `cat ../../config/vpic_header_list` ; do \
		link=`echo $file | sed 's,src,..,g'`
		ln -s $link .
	done
)

echo "generating Makefile.am for VPIC library"
[ ! -d lib ] && mkdir lib
config/create_lib_am > lib/Makefile.am

echo "calling libtoolize..."
glibtoolize --version &> /dev/null && LIBTOOLIZE=glibtoolize || LIBTOOLIZE=libtoolize
$LIBTOOLIZE -c -n -f --automake &> /dev/null || ln -s configure.ac configure.in
$LIBTOOLIZE -c -f --automake

echo "calling aclocal -I $cwd/m4"
aclocal -I $cwd/m4 > /dev/null 2>&1

echo "calling python testboot.py"
python config/testboot.py

echo "automake -af --foreign"
automake -af --foreign

echo "autoconf"
autoconf
