#! /usr/bin/env bash

rm -rf aclocal.m4
rm -rf autom4te.cache
rm -rf configure
rm -rf configure.ac
rm -rf config/config.guess
rm -rf config/config.sub
rm -rf config/depcomp
rm -rf config/install-sh
rm -rf config/ltmain.sh
rm -rf config/missing
rm -rf config/*.pyc
rm -rf config/version
rm -rf config/lib_version
rm -rf lib/Makefile.am
rm -rf `find . -type f -name "Makefile.in" | grep -v ".git"`
rm -rf `find . -type f -name "Makefile" | grep -v ".git"`
rm -rf `find test -type f -name "testsuite.at" | grep -v ".git"`
rm -rf `find test -type f -name "atlocal.in" | grep -v ".git"`
rm -rf `find test -type f -name "Makefile.am" | grep -v ".git"`
rm -rf `find test -type f -name "Makefile.in" | grep -v ".git"`
rm -rf `find test -type f -name "Makefile" | grep -v ".git"`
rm -rf src/include
