#! /usr/bin/env bash
################################################################################
# Copyright (c) 2012 Los Alamos National Security, LLC
# All rights reserved.
################################################################################

# get the most current tag
tag=`git describe --abbrev=0 --tags`

# get the date that the most current tag was created
since=`git show --date=relative $tag | head -n 3 | tail -n 1 | sed 's,^Date:[ \t]*,,g'`

# build will count the number of commits since the current tag was created
build=`git log --since="$since" | grep commit | wc -l`

echo $tag"."$build
