#! /usr/bin/env bash
#~----------------------------------------------------------------------------~#
# placeholder
#~----------------------------------------------------------------------------~#

#------------------------------------------------------------------------------#
# Get the path to the project from which this script was called
#------------------------------------------------------------------------------#

cinch_dir="$(dirname "$(dirname "$(readlink -f $0)")")"

#------------------------------------------------------------------------------#
# Check required environment variables
#------------------------------------------------------------------------------#

#------------------------------------------------------------------------------#
# Call CMake command
#------------------------------------------------------------------------------#

# The flag -rdynamic removes warnings of the form:
# Unable to find a safely writable symbol that corresponds to address 432af0
# (the closest match was "(null)" from "./lpi_2d_F6_test.Linux").  Writing out
# the raw address instead and keeping my fingers crossed.

cmake \
  -DCMAKE_BUILD_TYPE=Release \
  -DENABLE_COLOR_UNIT_TESTS=ON \
  -DENABLE_INTEGRATED_TESTS=ON \
  -DENABLE_UNIT_TESTS=OFF \
  -DUSE_ADVANCE_P_AUTOVEC=YES \
  -DCMAKE_C_FLAGS="-g -O3 -inline-forceinline -vec-threshold0 \
  -qopt-report=5 -qopt-report-phase=all -Winline \
  -qoverride-limits -no-ansi-alias -xMIC-AVX512 -qopenmp" \
  -DCMAKE_CXX_FLAGS="-g -O3 -inline-forceinline -vec-threshold0 \
  -qopt-report=5 -qopt-report-phase=all -Winline \
  -qoverride-limits -no-ansi-alias -xMIC-AVX512 -qopenmp" \
  $cinch_dir

#------------------------------------------------------------------------------#
# vim: syntax=sh
#------------------------------------------------------------------------------#

#~---------------------------------------------------------------------------~-#
# placeholder
#~---------------------------------------------------------------------------~-#
