#! /usr/bin/env bash
#~----------------------------------------------------------------------------~#
# placeholder
#~----------------------------------------------------------------------------~#

# To build on ciel(it)o:
# module swap PrgEnv-pgi PrgEnv-intel
# module load user_contrib
# module load cmake/3.4.0
# cd /path/to/code
# mkdir build
# cd build
# ../arch/cray-Release-sse
# make -j


#------------------------------------------------------------------------------#
# Get the path to the project from which this script was called
#------------------------------------------------------------------------------#

cinch_dir="$(dirname "$(dirname "$(readlink -f $0)")")"

#------------------------------------------------------------------------------#
# Check required environment variables
#------------------------------------------------------------------------------#

#------------------------------------------------------------------------------#
# Call CMake command
#------------------------------------------------------------------------------#

cmake \
  -DCMAKE_BUILD_TYPE=Release \
  -DENABLE_COLOR_UNIT_TESTS=OFF \
  -DENABLE_INTEGRATED_TESTS=OFF \
  -DENABLE_UNIT_TESTS=OFF \
  -DUSE_V4_SSE=ON \
  -DCMAKE_C_COMPILER=cc \
  -DCMAKE_CXX_COMPILER=CC \
  -DCMAKE_C_FLAGS="-dynamic -craype-verbose" \
  -DCMAKE_CXX_FLAGS="-dynamic -craype-verbose" \
  -DCMAKE_EXE_LINKER_FLAGS="-dynamic" \
  -DMPI_C_LIBRARIES="" \
  -DMPI_CXX_LIBRARIES="" \
  -DMPI_C_INCLUDE_PATH="" \
  -DMPI_CXX_INCLUDE_PATH="" \
  -DMPI_C_COMPILER="" \
  -DMPI_CXX_COMPILER="" \
  $cinch_dir

# To turn on unit/integrated tests add the following. Note that `which aprun`
# will ONLY WORK ON THE BACK END.
#  -DENABLE_COLOR_UNIT_TESTS=OFF \
#  -DENABLE_INTEGRATED_TESTS=OFF \
#  -DENABLE_UNIT_TESTS=OFF \
#  -DMPIEXEC=`which aprun` \
#  -DMPIEXEC_NUMPROC_FLAG="-n" \


#------------------------------------------------------------------------------#
# vim: syntax=sh
#------------------------------------------------------------------------------#

#~---------------------------------------------------------------------------~-#
# placeholder
#~---------------------------------------------------------------------------~-#
