#! /usr/bin/env bash
#~----------------------------------------------------------------------------~#
# placeholder
#~----------------------------------------------------------------------------~#

#------------------------------------------------------------------------------#
# Get the path to the project from which this script was called
#------------------------------------------------------------------------------#

cinch_dir="$(dirname "$(dirname "$(readlink -f $0)")")"

#------------------------------------------------------------------------------#
# Check required environment variables
#------------------------------------------------------------------------------#

#------------------------------------------------------------------------------#
# Call CMake command
#------------------------------------------------------------------------------#

# The flag -rdynamic removes warnings of the form:
# Unable to find a safely writable symbol that corresponds to address 432af0
# (the closest match was "(null)" from "./lpi_2d_F6_test.Linux").  Writing out
# the raw address instead and keeping my fingers crossed.

cmake \
  -DCMAKE_BUILD_TYPE=Release \
  -DENABLE_INTEGRATED_TESTS=OFF \
  -DENABLE_UNIT_TESTS=OFF \
  -DCMAKE_C_FLAGS="-O3 -rdynamic -inline-forceinline  \
  -qoverride-limits -no-ansi-alias -xMIC-AVX512" \
  -DCMAKE_CXX_FLAGS="-O3 -rdynamic -inline-forceinline \
  -qoverride-limits -no-ansi-alias -xMIC-AVX512" \
  -DUSE_V4_AVX2=ON \
  -DUSE_V16_AVX512=ON \
  $cinch_dir

#------------------------------------------------------------------------------#
# vim: syntax=sh
#------------------------------------------------------------------------------#

#~---------------------------------------------------------------------------~-#
# placeholder
#~---------------------------------------------------------------------------~-#
