#!/bin/tcsh -f
#
# Script to automate creation of directories for 2d lpi runs with vpic.
# This script should be executed from the directory from which vpic
# will be run prior to the run.  It ensures that the proper directory
# tree is created for the output files (rather than make a single
# directory with a large number of files).
#
if ! -d rundata mkdir rundata
if ! -d field mkdir field
if ! -d hydro mkdir hydro
if ! -d hydro/e mkdir hydro/e
if ! -d hydro/H mkdir hydro/H
if ! -d hydro/He mkdir hydro/He
if ! -d particle mkdir particle
if ! -d particle/e mkdir particle/e
if ! -d particle/H mkdir particle/H
if ! -d particle/He mkdir particle/He
if ! -d log mkdir log
if ! -d fft mkdir fft
if ! -d movie mkdir movie
if ! -d poynting mkdir poynting
if ! -d velocity mkdir velocity
if ! -d restart mkdir restart
