#! /usr/bin/env bash

echo "#ifndef symbols_hxx" > symbols.hxx
echo "#define symbols_hxx" >> symbols.hxx
echo >> symbols.hxx

new_field=`$1 $2 | grep " new_field" | \
	grep -v "advance" | awk '{print $1}'`
echo "const void * new_field = (void *)(0x$new_field);" >> symbols.hxx

delete_field=`$1 $2 | grep " delete_field" | \
	grep -v "advance" | awk '{print $1}'`
echo "const void * delete_field = (void *)(0x$delete_field);" >> symbols.hxx

new_material_coefficients=`$1 $2 | grep " new_material_coefficients" | \
	awk '{print $1}'`
echo "const void * new_material_coefficients = (void *)(0x$new_material_coefficients);" >> symbols.hxx

delete_material_coefficients=`$1 $2 | grep " delete_material_coefficients" | \
	awk '{print $1}'`
echo "const void * delete_material_coefficients = (void *)(0x$delete_material_coefficients);" >> symbols.hxx

advance_b=`$1 $2 | grep "advance_b" | \
	grep -v "v4_" | awk '{print $1}'`
echo "const void * advance_b = (void *)(0x$advance_b);" >> symbols.hxx

advance_e=`$1 $2 | grep "advance_e" | \
	grep -v "v4_" | grep -v "vfa_" | awk '{print $1}'`
echo "const void * advance_e = (void *)(0x$advance_e);" >> symbols.hxx

energy_f=`$1 $2 | grep "energy_f" | \
	grep -v "v4_" | grep -v "vfa_" | awk '{print $1}'`
echo "const void * energy_f = (void *)(0x$energy_f);" >> symbols.hxx

clear_jf=`$1 $2 | grep "clear_jf" | \
	grep -v "v4_" | awk '{print $1}'`
echo "const void * clear_jf = (void *)(0x$clear_jf);" >> symbols.hxx

synchronize_jf=`$1 $2 | grep "synchronize_jf" | \
	grep -v "v4_" | awk '{print $1}'`
echo "const void * synchronize_jf = (void *)(0x$synchronize_jf);" >> symbols.hxx

clear_rhof=`$1 $2 | grep "clear_rhof" | \
	grep -v "v4_" | awk '{print $1}'`
echo "const void * clear_rhof = (void *)(0x$clear_rhof);" >> symbols.hxx

synchronize_rho=`$1 $2 | grep "synchronize_rho" | \
	grep -v "v4_" | awk '{print $1}'`
echo "const void * synchronize_rho = (void *)(0x$synchronize_rho);" >> symbols.hxx

compute_rhob=`$1 $2 | grep "compute_rhob" | \
	grep -v "v4_" | grep -v "vfa_" | awk '{print $1}'`
echo "const void * compute_rhob = (void *)(0x$compute_rhob);" >> symbols.hxx

compute_curl_b=`$1 $2 | grep "compute_curl_b" | \
	grep -v "v4_" | grep -v "vfa_" | awk '{print $1}'`
echo "const void * compute_curl_b = (void *)(0x$compute_curl_b);" >> symbols.hxx

synchronize_tang_e_norm_b=`$1 $2 | grep "synchronize_tang_e_norm_b" | \
	grep -v "v4_" | awk '{print $1}'`
echo "const void * synchronize_tang_e_norm_b = (void *)(0x$synchronize_tang_e_norm_b);" >> symbols.hxx

compute_div_e_err=`$1 $2 | grep "compute_div_e_err" | \
	grep -v "v4_" | grep -v "vfa_" | awk '{print $1}'`
echo "const void * compute_div_e_err = (void *)(0x$compute_div_e_err);" >> symbols.hxx

compute_rms_div_e_err=`$1 $2 | grep "compute_rms_div_e_err" | \
	grep -v "v4_" | awk '{print $1}'`
echo "const void * compute_rms_div_e_err = (void *)(0x$compute_rms_div_e_err);" >> symbols.hxx

clean_div_e=`$1 $2 | grep "clean_div_e" | \
	grep -v "v4_" | grep -v "vfa_" | awk '{print $1}'`
echo "const void * clean_div_e = (void *)(0x$clean_div_e);" >> symbols.hxx

compute_div_b_err=`$1 $2 | grep "compute_div_b_err" | \
	grep -v "v4_" | awk '{print $1}'`
echo "const void * compute_div_b_err = (void *)(0x$compute_div_b_err);" >> symbols.hxx

compute_rms_div_b_err=`$1 $2 | grep "compute_rms_div_b_err" | \
	grep -v "v4_" | awk '{print $1}'`
echo "const void * compute_rms_div_b_err = (void *)(0x$compute_rms_div_b_err);" >> symbols.hxx

clean_div_b=`$1 $2 | grep "clean_div_b" | \
	grep -v "v4_" | awk '{print $1}'`
echo "const void * clean_div_b = (void *)(0x$clean_div_b);" >> symbols.hxx

echo >> symbols.hxx
echo "#endif // symbols_hxx" >> symbols.hxx
