#!/bin/sh
EXT=$1
BUILD=../../build.$EXT
CWD=`pwd`

TEST=accel;   echo $TEST; $BUILD $TEST; mpirun -np 1 --mca mpi_paffinity_alone 1 ../../mprelay.$EXT $CWD/$TEST.$EXT -tpp=$2
TEST=cyclo;   echo $TEST; $BUILD $TEST; mpirun -np 1 --mca mpi_paffinity_alone 1 ../../mprelay.$EXT $CWD/$TEST.$EXT -tpp=$2
TEST=inbndj;  echo $TEST; $BUILD $TEST; mpirun -np 1 --mca mpi_paffinity_alone 1 ../../mprelay.$EXT $CWD/$TEST.$EXT -tpp=$2
TEST=interpe; echo $TEST; $BUILD $TEST; mpirun -np 1 --mca mpi_paffinity_alone 1 ../../mprelay.$EXT $CWD/$TEST.$EXT -tpp=$2
TEST=outbndj; echo $TEST; $BUILD $TEST; mpirun -np 1 --mca mpi_paffinity_alone 1 ../../mprelay.$EXT $CWD/$TEST.$EXT -tpp=$2
TEST=pcomm;   echo $TEST; $BUILD $TEST; mpirun -np 8 --mca mpi_paffinity_alone 1 ../../mprelay.$EXT $CWD/$TEST.$EXT -tpp=$2
TEST=rngconv; echo $TEST; $BUILD $TEST; mpirun -np 1 --mca mpi_paffinity_alone 1 ../../mprelay.$EXT $CWD/$TEST.$EXT -tpp=$2
TEST=rngseq;  echo $TEST; $BUILD $TEST; mpirun -np 1 --mca mpi_paffinity_alone 1 ../../mprelay.$EXT $CWD/$TEST.$EXT -tpp=$2
TEST=v4;      echo $TEST; $BUILD $TEST; mpirun -np 1 --mca mpi_paffinity_alone 1 ../../mprelay.$EXT $CWD/$TEST.$EXT -tpp=$2
